### ISSUE TITLE
Configure @TryPyramid Twitter account

### ISSUE THREAD

**Issue by stevepiercy** [Pylons/trypyramid.com#39]
# Todos
- [ ] Determine who should have access and grant it (currently only @stevepiercy).

The following are the only relevant settings.
## Profile
- [x] Profile photo
- [ ] Header photo
- [ ] Theme color (currently #bf1e2d)
- [ ] Bio
- [ ] Location
- [x] Birthday (due to COPPA, Pyramid is too young to use Twitter, lol)
## Follow
- [ ] Following
- [ ] Followers
## Lists
- [ ] Subscribed to
- [ ] Member of
### Account
- [ ] Email (currently ___@stevepiercy.com)
- [ ] Time zone (currently GMT-08:00 Pacific)
### Email notifications
- [ ] Only My Tweets get a reply or I'm mentioned in a Tweet, I'm followed by someone new, I'm sent a direct message
### Web notifications
- [ ] Only My Tweets get a reply or I'm mentioned in a Tweet, I'm followed by someone new, I'm sent a direct message
### Design
- [ ] Background image (optionally tiled)

**Comment by stevepiercy** [comment]
Consolidated with `@PylonsProject`, so no need exists for this issue. Closing.
